
<!DOCTYPE html
  PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>7.4.&nbsp;Verificare i casi di errore</title>
<link rel="stylesheet" href="/css/diveintopython.css" type="text/css" />
<link rev="made" href="josh@servercobra.com" />
<meta name="generator" content="DocBook XSL Stylesheets V1.52.2" />
<meta name="keywords" content="Python, Dive Into Python, tutorial, object-oriented, programming, documentation, book, free" />
<meta name="description" content="Python from novice to pro" />
<link rel="home" href="http://it.diveintopython.net/" title="Dive Into Python" />
<link rel="up" href="http://it.diveintopython.net/unit_testing/index.html" title="Capitolo&nbsp;7.&nbsp;Test delle unit&agrave; di codice" />
<link rel="previous" href="http://it.diveintopython.net/unit_testing/testing_for_success.html" title="7.3.&nbsp;Verificare i casi di successo" />
<link rel="next" href="http://it.diveintopython.net/unit_testing/testing_for_sanity.html" title="7.5.&nbsp;Verificare la consistenza" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9740779-18']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script></head>
<body>
<style type="text/css">body{margin-top:0!important;padding-top:0!important;min-width:800px!important;}#wm-ipp a:hover{text-decoration:underline!important;}</style>
<table id="Header" width="100%" border="0" cellpadding="0" cellspacing="0" summary="">
<tr>
<td id="breadcrumb" colspan="5" align="left" valign="top">You are here: <a href="http://it.diveintopython.net/index.html">Partenza</a>&nbsp;&gt;&nbsp;<a href="http://it.diveintopython.net/toc/index.html">Dive Into Python</a>&nbsp;&gt;&nbsp;<a href="http://it.diveintopython.net/unit_testing/index.html">Test delle unit&agrave; di codice</a>&nbsp;&gt;&nbsp;<span class="thispage">Verificare i casi di errore</span></td>
<td id="navigation" align="right" valign="top">&nbsp;&nbsp;&nbsp;<a href="http://it.diveintopython.net/unit_testing/testing_for_success.html" title="Indietro: “Verificare i casi di successo”">&lt;&lt;</a>&nbsp;&nbsp;&nbsp;<a href="http://it.diveintopython.net/unit_testing/testing_for_sanity.html" title="Avanti: “Verificare la consistenza”">&gt;&gt;</a></td>
</tr>
<tr>
<td colspan="3" id="logocontainer">
<h1 id="logo"><a href="http://it.diveintopython.net/index.html" accesskey="1">Dive Into Python</a></h1>
<p id="tagline">Python per programmatori esperti</p>
</td>
<td colspan="3" align="right">
<form id="search" method="GET" action="http://www.google.com/custom">
<p><label for="q" accesskey="4">Find:&nbsp;</label><input type="text" id="q" name="q" size="20" maxlength="255" value=" " /> <input type="submit" value="Search" /><input type="hidden" name="cof" value="LW:752;L:http://diveintopython.org/images/diveintopython.png;LH:42;AH:left;GL:0;AWFID:3ced2bb1f7f1b212;" /><input type="hidden" name="domains" value="diveintopython.org" /><input type="hidden" name="sitesearch" value="diveintopython.org" /></p>
</form>
</td>
</tr>
</table>
<div class="section" lang="it">
<div class="titlepage">
<div>
<div>
<h2 class="title"><a name="roman.failure"></a>7.4.&nbsp;Verificare i casi di errore
                  </h2>
</div>
</div>
<div></div>
</div>
<div class="abstract">
<p>
               	Non &egrave; abbastanza  verificare che la nostra funzione abbia
               	successo quando gli input sono validi; occorre anche
               	verificare che la funzione vada in errore quando riceve
               	input non validi. E non basta che vada in errore: deve farlo
               	nel modo che ci si aspetta.
               
            </p>
</div>
<p>
            
            	Ricordiamoci di
            	<a href="http://it.diveintopython.net/unit_testing/index.html#roman.requirements"> due altri
               	requisiti</a> per <tt class="function">toRoman</tt>:
            
         </p>
<div class="orderedlist">
<ol start="2" type="1">
<li>
                  	La funzione <tt class="function">toRoman</tt> dovrebbe andare in errore con un intero
                  	fuori dall'intervallo da <tt class="constant">1</tt> a <tt class="literal">3999</tt>.
                  
               </li>
<li>
                  	La funzione <tt class="function">toRoman</tt> dovrebbe andare in
                  	errore con un numero non decimale.
                  
               </li>
</ol>
</div>
<p>
            	In <span class="application">Python</span>, le funzioni indicano gli errori sollevando
            	<a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html" title="4.10.&nbsp;Gestire le eccezioni">eccezioni</a>, ed
            	il modulo <tt class="filename">unittest</tt> fornisce metodi per verificare
            	se una funzione solleva una particolare eccezione quando
            	riceve un input non valido.
            
         </p>
<div class="example"><a name="roman.tobadinput.example"></a><h3 class="title">Esempio&nbsp;7.3.&nbsp;Verificare la funzione <tt class="function">toRoman</tt> con input non validi
            </h3><pre class="programlisting"><span class="pykeyword">
class</span> ToRomanBadInput(unittest.TestCase):                            
    <span class="pykeyword">def</span><span class="pyclass"> testTooLarge</span>(self):                                          
        <span class="pystring">"""toRoman should fail with large input"""</span>                   
        self.assertRaises(roman.OutOfRangeError, roman.toRoman, 4000) <a name="roman.failure.1.1"></a><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" />

    <span class="pykeyword">def</span><span class="pyclass"> testZero</span>(self):                                              
        <span class="pystring">"""toRoman should fail with 0 input"""</span>                       
        self.assertRaises(roman.OutOfRangeError, roman.toRoman, 0)    <a name="roman.failure.1.2"></a><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" />

    <span class="pykeyword">def</span><span class="pyclass"> testNegative</span>(self):                                          
        <span class="pystring">"""toRoman should fail with negative input"""</span>                
        self.assertRaises(roman.OutOfRangeError, roman.toRoman, -1)  

    <span class="pykeyword">def</span><span class="pyclass"> testDecimal</span>(self):                                           
        <span class="pystring">"""toRoman should fail with non-integer input"""</span>             
        self.assertRaises(roman.NotIntegerError, roman.toRoman, 0.5)  <a name="roman.failure.1.3"></a><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" /></pre><div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/unit_testing/testing_for_failure.html#roman.failure.1.1"><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	La classe <tt class="classname">TestCase</tt> del modulo <tt class="filename">unittest</tt>
                        	fornisce il metodo <tt class="function">assertRaises</tt>, che accetta i seguenti
                        	argomenti: l'eccezione attesa, la funzione sotto test e gli
                        	argomenti da passare alla funzione. Se la funzione sotto
                        	test richiede pi&ugrave; di un argomento, passateli nell'ordine
                        	giusto al metodo <tt class="function">assertRaises</tt> e questi li passer&agrave; a sua
                        	volta nello stesso ordine alla funzione da verificare.
                        	Fate attenzione a quello che si sta facendo a questo punto:
                        	invece di chiamare direttamente <tt class="function">toRoman</tt> e verificare
                        	manualmente che sollevi una particolare eccezione
                        	(incapsulandola in un
                        	<a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html" title="4.10.&nbsp;Gestire le eccezioni">blocco <tt class="literal">try...except</tt></a>),
                        	il metodo <tt class="function">assertRaises</tt> si incarica al posto nostro di
                        	chiamare <tt class="function">toRoman</tt> con il suo argomento (4000) e si assicura
                        	che sollevi l'eccezione 
                        	<tt class="errorcode">roman.OutOfRangeError</tt>. Ho ricordato di
                        	recente com'&egrave; comodo che 
                        	<a href="http://it.diveintopython.net/getting_to_know_python/everything_is_an_object.html" title="2.4.&nbsp;Tutto &egrave; un oggetto">tutto in <span class="application">Python</span> sia un
                           	oggetto</a>, incluse funzioni ed eccezioni?
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/unit_testing/testing_for_failure.html#roman.failure.1.2"><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Oltre ad effettuare test con numeri troppo grandi, abbiamo
                        	bisogno di fare test con numeri troppo piccoli. Ricordiamoci
                        	che i numeri romani non possono esprimere lo zero o quantit&agrave;
                        	negative, per cui &egrave; opportuno predisporre dei test per questi
                        	casi (<tt class="function">testZero</tt> e
                        	<tt class="function">testNegative</tt>). In
                        	<tt class="function">testZero</tt>, si sta verificando che
                        	<tt class="function">toRoman</tt> sollevi un'eccezione
                        	<tt class="errorcode">roman.OutOfRangeError</tt> quando &egrave; chiamata
                        	con <tt class="constant">0</tt>; se <span class="emphasis"><em>non</em></span> solleva tale eccezione
                        	(sia che restituisca un valore o che sollevi un'eccezione
                        	diversa), il test &egrave; considerato fallito.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/unit_testing/testing_for_failure.html#roman.failure.1.3"><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        
                        	Il <a href="http://it.diveintopython.net/unit_testing/index.html#roman.requirements">requisito #3</a>
                        	specifica che la funzione <tt class="function">toRoman</tt>
                        	non pu&ograve; accettare un numero decimale, perci&ograve; in questo
                        	punto si sta verificando che la funzione <tt class="function">toRoman</tt>
                        	sollevi un'eccezione
                        	<tt class="errorcode">roman.NotIntegerError</tt> quando chiamata
                        	con un parametro decimale (<tt class="literal">0.5</tt>). Se la
                        	funzione <tt class="function">toRoman</tt> non solleva un eccezione
                        	<tt class="errorcode">roman.NotIntegerError</tt>, questo test
                        	&egrave; considerato fallito.
                        
                     </td>
</tr>
</table>
</div>
</div>
<p>
            	I prossimi due
            	<a href="http://it.diveintopython.net/unit_testing/index.html#roman.requirements">requisiti</a>
            	sono simili ai primi tre, fatta eccezione per il fatto
            	che si applicano a <tt class="function">fromRoman</tt> invece che a <tt class="function">toRoman</tt>.
            
         </p>
<div class="orderedlist">
<ol start="4" type="1">
<li>
                  	La funzione <tt class="function">fromRoman</tt> dovrebbe accettare un valido numero
                  	romano e restituire il numero arabo corrispondente.
                  
               </li>
<li>
                  	La funzione <tt class="function">fromRoman</tt> dovrebbe andare in errore quando &egrave;
                  	chiamata con un numero romano non valido.
                  
               </li>
</ol>
</div>
<p>
            	IL requisito #4 &egrave; gestito nello stesso modo del
            	<a href="http://it.diveintopython.net/unit_testing/testing_for_success.html#roman.testtoromanknownvalues.example" title="Esempio&nbsp;7.2.&nbsp;testToRomanKnownValues">requisito
               	#1</a>, iterando attraverso un campione di valori noti ed
            	effettuando una verifica con ciascuno di essi. Il requisito #5
            	&egrave; gestito alla stessa maniera dei requisiti #2 e #3,
            	verificando la funzione con una serie di input non validi e
            	controllando che sollevi le opportune eccezioni.
            
         </p>
<div class="example"><a name="roman.frombadinput.example"></a><h3 class="title">Esempio&nbsp;7.4.&nbsp;Verificare <tt class="function">fromRoman</tt> con input non validi
            </h3><pre class="programlisting"><span class="pykeyword">
class</span> FromRomanBadInput(unittest.TestCase):                                      
    <span class="pykeyword">def</span><span class="pyclass"> testTooManyRepeatedNumerals</span>(self):                                       
        <span class="pystring">"""fromRoman should fail with too many repeated numerals"""</span>              
        <span class="pykeyword">for</span> s <span class="pykeyword">in</span> (<span class="pystring">'MMMM'</span>, <span class="pystring">'DD'</span>, <span class="pystring">'CCCC'</span>, <span class="pystring">'LL'</span>, <span class="pystring">'XXXX'</span>, <span class="pystring">'VV'</span>, <span class="pystring">'IIII'</span>):             
            self.assertRaises(roman.InvalidRomanNumeralError, roman.fromRoman, s) <a name="roman.failure.2.1"></a><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" />

    <span class="pykeyword">def</span><span class="pyclass"> testRepeatedPairs</span>(self):                                                 
        <span class="pystring">"""fromRoman should fail with repeated pairs of numerals"""</span>              
        <span class="pykeyword">for</span> s <span class="pykeyword">in</span> (<span class="pystring">'CMCM'</span>, <span class="pystring">'CDCD'</span>, <span class="pystring">'XCXC'</span>, <span class="pystring">'XLXL'</span>, <span class="pystring">'IXIX'</span>, <span class="pystring">'IVIV'</span>):               
            self.assertRaises(roman.InvalidRomanNumeralError, roman.fromRoman, s)

    <span class="pykeyword">def</span><span class="pyclass"> testMalformedAntecedent</span>(self):                                           
        <span class="pystring">"""fromRoman should fail with malformed antecedents"""</span>                   
        <span class="pykeyword">for</span> s <span class="pykeyword">in</span> (<span class="pystring">'IIMXCC'</span>, <span class="pystring">'VX'</span>, <span class="pystring">'DCM'</span>, <span class="pystring">'CMM'</span>, <span class="pystring">'IXIV'</span>,
                  <span class="pystring">'MCMC'</span>, <span class="pystring">'XCX'</span>, <span class="pystring">'IVI'</span>, <span class="pystring">'LM'</span>, <span class="pystring">'LD'</span>, <span class="pystring">'LC'</span>):                       
            self.assertRaises(roman.InvalidRomanNumeralError, roman.fromRoman, s)</pre><div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/unit_testing/testing_for_failure.html#roman.failure.2.1"><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Non c'&egrave; molto da dire su queste linee di codice; lo schema &egrave;
                        	esattamente lo stesso che &egrave; stato usato per verificare
                        	<tt class="function">toRoman</tt> con input non validi. Faccio brevemente notare che
                        	si &egrave; definita una nuova eccezione:
                        	<tt class="errorcode">roman.InvalidRomanNumeralError</tt>.
                        	Questo fa un totale di tre eccezioni specifiche che bisogner&agrave;
                        	definire in <tt class="filename">roman.py</tt> (contando anche
                        	<tt class="errorcode">roman.OutOfRangeError</tt> e
                        	<tt class="errorcode">roman.NotIntegerError</tt>). Vedremo come
                        	definire queste eccezioni specifiche quando cominceremo
                        	effettivamente a scrivere <tt class="filename">roman.py</tt>, pi&ugrave; avanti in
                        	questo capitolo.
                        
                     </td>
</tr>
</table>
</div>
</div>
</div>
<table class="Footer" width="100%" border="0" cellpadding="0" cellspacing="0" summary="">
<tr>
<td width="35%" align="left"><br /><a class="NavigationArrow" href="http://it.diveintopython.net/unit_testing/testing_for_success.html">&lt;&lt;&nbsp;Verificare i casi di successo</a></td>
<td width="30%" align="center"><br />&nbsp;<span class="divider">|</span>&nbsp;<a href="http://it.diveintopython.net/unit_testing/index.html#roman.divein" title="7.1.&nbsp;Immergersi">1</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/romantest.html" title="7.2.&nbsp;Introduzione al modulo romantest.py">2</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/testing_for_success.html" title="7.3.&nbsp;Verificare i casi di successo">3</a> <span class="divider">|</span> <span class="thispage">4</span> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/testing_for_sanity.html" title="7.5.&nbsp;Verificare la consistenza">5</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/stage_1.html" title="7.6.&nbsp;roman.py, fase 1">6</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/stage_2.html" title="7.7.&nbsp;roman.py, fase 2">7</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/stage_3.html" title="7.8.&nbsp;roman.py, fase 3">8</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/stage_4.html" title="7.9.&nbsp;roman.py, fase 4">9</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/stage_5.html" title="7.10.&nbsp;roman.py, fase 5">10</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/handling_bugs.html" title="7.11.&nbsp;Come gestire gli errori di programmazione">11</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/handling_changing_requirements.html" title="7.12.&nbsp;Gestire il cambiamento di requisiti">12</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/refactoring.html" title="7.13.&nbsp;Rifattorizzazione">13</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/postscript.html" title="7.14.&nbsp;Postscritto">14</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/unit_testing/summary.html" title="7.15.&nbsp;Sommario">15</a>&nbsp;<span class="divider">|</span>&nbsp;
            </td>
<td width="35%" align="right"><br /><a class="NavigationArrow" href="http://it.diveintopython.net/unit_testing/testing_for_sanity.html">Verificare la consistenza&nbsp;&gt;&gt;</a></td>
</tr>
<tr>
<td colspan="3"><br /></td>
</tr>
</table>
<div class="Footer">
<p class="copyright">Copyright &copy; 2000, 2001, 2002, 2003 <a href="mailto:josh@servercobra.com">Mark Pilgrim</a></p>
<p class="copyright">Copyright &copy; 2003 Si veda l'appendice <span class="emphasis"><em>E: "Storia delle revisioni"</em></span></p>
</div>
</body>
</html>
