
<!DOCTYPE html
  PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>4.10.&nbsp;Gestire le eccezioni</title>
<link rel="stylesheet" href="/css/diveintopython.css" type="text/css" />
<link rev="made" href="josh@servercobra.com" />
<meta name="generator" content="DocBook XSL Stylesheets V1.52.2" />
<meta name="keywords" content="Python, Dive Into Python, tutorial, object-oriented, programming, documentation, book, free" />
<meta name="description" content="Python from novice to pro" />
<link rel="home" href="http://it.diveintopython.net/" title="Dive Into Python" />
<link rel="up" href="http://it.diveintopython.net/object_oriented_framework/index.html" title="Capitolo&nbsp;4.&nbsp;Una struttura orientata agli oggetti" />
<link rel="previous" href="http://it.diveintopython.net/object_oriented_framework/private_functions.html" title="4.9.&nbsp;Funzioni private" />
<link rel="next" href="http://it.diveintopython.net/object_oriented_framework/file_objects.html" title="4.11.&nbsp;Oggetti file" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9740779-18']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script></head>
<body>
<style type="text/css">body{margin-top:0!important;padding-top:0!important;min-width:800px!important;}#wm-ipp a:hover{text-decoration:underline!important;}</style>
<table id="Header" width="100%" border="0" cellpadding="0" cellspacing="0" summary="">
<tr>
<td id="breadcrumb" colspan="5" align="left" valign="top">You are here: <a href="http://it.diveintopython.net/index.html">Partenza</a>&nbsp;&gt;&nbsp;<a href="http://it.diveintopython.net/toc/index.html">Dive Into Python</a>&nbsp;&gt;&nbsp;<a href="http://it.diveintopython.net/object_oriented_framework/index.html">Una struttura orientata agli oggetti</a>&nbsp;&gt;&nbsp;<span class="thispage">Gestire le eccezioni</span></td>
<td id="navigation" align="right" valign="top">&nbsp;&nbsp;&nbsp;<a href="http://it.diveintopython.net/object_oriented_framework/private_functions.html" title="Indietro: “Funzioni private”">&lt;&lt;</a>&nbsp;&nbsp;&nbsp;<a href="http://it.diveintopython.net/object_oriented_framework/file_objects.html" title="Avanti: “Oggetti file”">&gt;&gt;</a></td>
</tr>
<tr>
<td colspan="3" id="logocontainer">
<h1 id="logo"><a href="http://it.diveintopython.net/index.html" accesskey="1">Dive Into Python</a></h1>
<p id="tagline">Python per programmatori esperti</p>
</td>
<td colspan="3" align="right">
<form id="search" method="GET" action="http://www.google.com/custom">
<p><label for="q" accesskey="4">Find:&nbsp;</label><input type="text" id="q" name="q" size="20" maxlength="255" value=" " /> <input type="submit" value="Search" /><input type="hidden" name="cof" value="LW:752;L:http://diveintopython.org/images/diveintopython.png;LH:42;AH:left;GL:0;AWFID:3ced2bb1f7f1b212;" /><input type="hidden" name="domains" value="diveintopython.org" /><input type="hidden" name="sitesearch" value="diveintopython.org" /></p>
</form>
</td>
</tr>
</table>
<div class="section" lang="it">
<div class="titlepage">
<div>
<div>
<h2 class="title"><a name="fileinfo.exception"></a>4.10.&nbsp;Gestire le eccezioni
                  </h2>
</div>
</div>
<div></div>
</div>
<div class="abstract">
<p>
               	Come molti linguaggi orientati agli oggetti, <span class="application">Python</span> consente
               	la manipolazione delle eccezioni tramite i blocchi
               	<tt class="literal">try...except</tt>.
               
            </p>
</div><a name="compare.exceptions.java"></a><table class="note" border="0" summary="">
<tr>
<td rowspan="2" align="center" valign="top" width="1%"><img src="http://it.diveintopython.net/images/note.png" alt="Nota" title="" width="24" height="24" /></td>
</tr>
<tr>
<td colspan="2" align="left" valign="top" width="99%">
<span class="application">Python</span> usa <tt class="literal">try...except</tt> per gestire le eccezioni e
                  	<tt class="literal">raise</tt> per generarle. <span class="application">Java</span> e <span class="application"><span class="acronym">C++</span></span> usano
                  	<tt class="literal">try...catch</tt> per gestirle e
                  	<tt class="literal">throw</tt> per generarle.
                  
               </td>
</tr>
</table>
<p>
            	Se conoscete gi&agrave; tutto riguardo le eccezioni, potete saltare
            	questa sezione. Se siete rimasti bloccati programmando in un
            	linguaggio minore che non ha la gestione delle eccezioni, o
            	avete usato un linguaggio vero, ma senza usare le eccezioni,
            	questa sezione &egrave; molto importante.
            
         </p>
<p>
            	Le eccezioni sono ovunque in <span class="application">Python</span>; virtualmente ogni
            	modulo nella libreria standard di <span class="application">Python</span> le usa e
            	<span class="application">Python</span> stesso le solleva in molte differenti
            	circostanze.
            	Le avete gi&agrave; viste spesso in questo libro.
            
         </p>
<div class="itemizedlist">
<ul>
<li>
<a href="http://it.diveintopython.net/getting_to_know_python/dictionaries.html#odbchelper.dict.define" title="Esempio&nbsp;2.10.&nbsp;Definire un dizionario">Accedere ad una chiave
                     	non esistente di un dizionario </a> solleva una eccezione
                  	<tt class="errorcode">KeyError</tt>.
                  
               </li>
<li>
<a href="http://it.diveintopython.net/getting_to_know_python/lists.html#odbchelper.list.search" title="Esempio&nbsp;2.20.&nbsp;Ricerca in una lista">Ricercare in una lista
                     	un valore non esistente</a> solleva un'eccezione
                  	<tt class="errorcode">ValueError</tt>.
                  	
               </li>
<li>
<a href="http://it.diveintopython.net/getting_to_know_python/tuples.html#odbchelper.tuplemethods" title="Esempio&nbsp;2.24.&nbsp;Le tuple non hanno metodi">Chiamare un metodo non
                     	esistente</a> solleva un'eccezione
                  	<tt class="errorcode">AttributeError</tt>.
                  	
               </li>
<li>
<a href="http://it.diveintopython.net/getting_to_know_python/declaring_variables.html#odbchelper.unboundvariable" title='Esempio&nbsp;2.26.&nbsp;
        Riferirsi ad una variabile non assegnata (unbound, 
        "slegata" n.d.T.)
'>Riferirsi ad una
                     	variabile non esistente</a> solleva un'eccezione
                  	<tt class="errorcode">NameError</tt>.
                  	
               </li>
<li>
<a href="http://it.diveintopython.net/getting_to_know_python/formatting_strings.html#odbchelper.stringformatting.coerce" title="Esempio&nbsp;2.30.&nbsp;Formattazione delle stringhe contro  concatenazione">Mischiare
                     	tipi di dato senza coercizione</a> solleva un'eccezione
                  	<tt class="errorcode">TypeError</tt>.
                  	
               </li>
</ul>
</div>
<p>
            	In ognuno di questi casi, stavamo semplicemente giocando
            	intorno all'<span class="acronym">IDE</span> di <span class="application">Python</span>: si incappa in un errore,
            	l'eccezione viene stampata (a seconda del
            	vostro <span class="acronym">IDE</span>, in un
            	intenzionale e stonante ombra di rosso) e niente pi&ugrave;. Questa
            	viene chiamata eccezione <span class="emphasis"><em>non gestita</em></span>;
            	quando l'eccezione veniva sollevata, non c'era codice che la
            	notasse esplicitamente e se ne occupasse, perci&ograve; tutto
            	proseguiva secondo il comportamento predefinito di <span class="application">Python</span>,
            	stampando alcune informazioni di debug e terminando il
            	programma. Nell'<span class="acronym">IDE</span> questo non &egrave; un grosso problema, ma se
            	accade mentre il vostro programma <span class="application">Python</span> reale &egrave; in
            	esecuzione, l'intero programma va incontro ad
            	un'improvvisa e poco piacevole interruzione.
               <sup>[<a name="d0e10936" href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#ftn.d0e10936">6</a>]</sup>
</p>
<p>
            	Un'eccezione non deve tuttavia comportare il crash dell'intero
            	programma. Le eccezioni, quando sollevate, possono essere
            	<span class="emphasis"><em>gestite</em></span>. Qualche volta un'eccezione &egrave;
            	autentica perch&eacute; c'&egrave; un difetto nel vostro codice (come
            	l'accesso ad una variabile inesistente), spesso per&ograve;
            	un'eccezione &egrave; qualcosa che avevate previsto. Se,
            	ad esempio, state aprendo
            	un file, questi potrebbe non esistere; se vi state
            	connettendo
            	ad un database, potrebbe non essere disponibile o
            	potreste non avere i necessari requisiti di sicurezza per
            	accedervi. Se sapete che una linea di codice potrebbe
            	sollevare un'eccezione, dovreste gestirla  usando un blocco
            	<tt class="literal">try...except</tt>.
            
         </p>
<div class="example"><a name="d0e10948"></a><h3 class="title">Esempio&nbsp;4.21.&nbsp;Aprire un file inesistente</h3><pre class="screen"><tt class="prompt">&gt;&gt;&gt; </tt><span class="userinput">fsock = open(<span class="pystring">"/notthere"</span>, <span class="pystring">"r"</span>)</span>      <a name="fileinfo.exceptions.1.1"></a><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" />
<span class="traceback">Traceback (innermost last):
  File "&lt;interactive input&gt;", line 1, in ?
IOError: [Errno 2] No such file or directory: '/notthere'</span>
<tt class="prompt">&gt;&gt;&gt; </tt><span class="userinput"><span class="pykeyword">try</span>:</span>
<tt class="prompt">...     </tt><span class="userinput">fsock = open(<span class="pystring">"/notthere"</span>)</span>       <a name="fileinfo.exceptions.1.2"></a><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" />
<tt class="prompt">... </tt><span class="userinput"><span class="pykeyword">except</span> IOError:</span>                     <a name="fileinfo.exceptions.1.3"></a><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" />
<tt class="prompt">...     </tt><span class="userinput"><span class="pykeyword">print</span> <span class="pystring">"The file does not exist, exiting gracefully"</span></span>
<tt class="prompt">... </tt><span class="userinput"><span class="pykeyword">print</span> <span class="pystring">"This line will always print"</span></span> <a name="fileinfo.exceptions.1.4"></a><img src="http://it.diveintopython.net/images/callouts/4.png" alt="4" border="0" width="12" height="12" />
<span class="computeroutput">The file does not exist, exiting gracefully
This line will always print</span></pre><div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.1.1"><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Usando la funzione built-in <tt class="function">open</tt>, possiamo provare ad aprire
                        	un file in lettura (molte altre cose su <tt class="function">open</tt> nella prossima
                        	sezione). Il file non esiste, quindi viene sollevata
                        	l'eccezione <tt class="errorcode">IOError</tt>. Dato che non abbiamo provveduto a
                        	gestire l'eccezione <tt class="errorcode">IOError</tt>,
                        	<span class="application">Python</span> si limita a stampare alcune informazioni di debug di
                        	quello che &egrave; accaduto ed a terminare il programma.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.1.2"><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Stiamo provando ad aprire lo stesso file inesistente ma
                        	questa volta lo stiamo facendo all'interno di un blocco
                        	<tt class="literal">try...except</tt>.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.1.3"><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Quando il metodo <tt class="function">open</tt> solleva un'eccezione <tt class="errorcode">IOError</tt>, siamo
                        	pronti per gestirla. <tt class="literal">except IOError:</tt> questa
                        	linea cattura l'eccezione ed esegue il nostro blocco di
                        	codice, che in questo caso si limita a stampare un messaggio
                        	di errore pi&ugrave; cortese.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.1.4"><img src="http://it.diveintopython.net/images/callouts/4.png" alt="4" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Una volta che un'eccezione &egrave; stata gestita, il processo
                        	continua con la linea che segue il blocco <tt class="literal">try...except</tt>.
                        	Notate che questa linea stamper&agrave; sempre se l'eccezione
                        	avviene oppure no. Se aveste veramente un file chiamato
                        	<tt class="filename">notthere</tt> nella vostra root directory,
                        	la chiamata ad <tt class="function">open</tt> funzionerebbe, la clausola
                        	<tt class="literal">except</tt> sarebbe ignorata e questa linea
                        	verrebbe ancora eseguita.
                        
                     </td>
</tr>
</table>
</div>
</div>
<p>
            	Le eccezioni possono sembrare ostiche (dopotutto, se non
            	catturate l'eccezione, il vostro intero programma terminer&agrave;),
            	ma considerate l'alternativa. Vorreste veramente ottenere un
            	oggetto file riferito ad un file non esistente? Dovreste in
            	ogni caso controllarne la validit&agrave; e se ve ne dimenticate,
            	il vostro programma vi darebbe strani errori da qualche parte
            	nelle linee seguenti e voi sareste costretti a ricontrollare
            	l'intero codice, alla ricerca della causa del problema.
            	Sono sicuro che lo avete gi&agrave; fatto; non &egrave; divertente. Con le
            	eccezioni, gli errori vengono rilevati immediatamente e potete
            	risolvere il problema alla radice, gestendoli in modo
            	standard.
            
         </p>
<p>
            	Ci sono molti altri usi delle eccezioni oltre alla gestione
            	degli errori. Un uso comune nella libreria standard <span class="application">Python</span>
            	consiste nel provare ad importare un modulo e poi provare se
            	funzioni o meno. Importare un modulo che non esiste causa il
            	sollevamento dell'eccezione <tt class="errorcode">ImportError</tt>. Potete usarla per
            	definire molteplici livelli di funzionalit&agrave;, basati su quali
            	moduli sono disponibili a run-time, o per supportare
            	molteplici
            	piattaforme (dove il codice specifico per ogni piattaforma &egrave;
            	suddiviso in moduli differenti).
            
         </p>
<p>
            	Potete inoltre definire le vostre stesse eccezioni,
            	creando una
            	classe che eredita dalla classe built-in
            	<tt class="classname">Exception</tt> e sollevare le vostre
            	eccezioni tramite il comando <tt class="function">raise</tt>.
            	Questo va al di fuori dallo scopo di questa sezione ma
            	leggete gli ulteriori paragrafi se siete interessati.
            
            
         </p>
<div class="example"><a name="crossplatform.example"></a><h3 class="title">Esempio&nbsp;4.22.&nbsp;Supportare le funzionalit&agrave; specifiche per piattaforma</h3>
<p>
               	Questo codice proviene dal modulo
               	<tt class="filename">getpass</tt>, un modulo
               	wrapper per ottenere password dagli utenti. Ottenere una
               	password &egrave; significativamente differente da piattaforme
               	<span class="acronym">UNIX</span>, Windows e <span class="abbrev">Mac</span> <span class="acronym">OS</span>, ma questo codice incapsula tutte
               	differenze.
               
            </p><pre class="programlisting">
  <span class="pycomment"># Bind the name getpass to the appropriate function</span>
  <span class="pykeyword">try</span>:
      <span class="pykeyword">import</span> termios, TERMIOS                     <a name="fileinfo.exceptions.2.1"></a><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" />
  <span class="pykeyword">except</span> ImportError:
      <span class="pykeyword">try</span>:
          <span class="pykeyword">import</span> msvcrt                           <a name="fileinfo.exceptions.2.2"></a><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" />
      <span class="pykeyword">except</span> ImportError:
          <span class="pykeyword">try</span>:
              <span class="pykeyword">from</span> EasyDialogs <span class="pykeyword">import</span> AskPassword <a name="fileinfo.exceptions.2.3"></a><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" />
          <span class="pykeyword">except</span> ImportError:
              getpass = default_getpass           <a name="fileinfo.exceptions.2.4"></a><img src="http://it.diveintopython.net/images/callouts/4.png" alt="4" border="0" width="12" height="12" />
          <span class="pykeyword">else</span>:                                   <a name="fileinfo.exceptions.2.5"></a><img src="http://it.diveintopython.net/images/callouts/5.png" alt="5" border="0" width="12" height="12" />
              getpass = AskPassword
      <span class="pykeyword">else</span>:
          getpass = win_getpass
  <span class="pykeyword">else</span>:
      getpass = unix_getpass</pre><div class="calloutlist">
<table border="0" summary="Callout list">
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.2.1"><img src="http://it.diveintopython.net/images/callouts/1.png" alt="1" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
<tt class="filename">termios</tt> &egrave; un modulo specifico <span class="acronym">UNIX</span>, che rende disponibile
                        	un controllo di basso livello sul terminale di input. Se il
                        	modulo non &egrave; disponibile sul vostro sistema o non &egrave;
                        	supportato, <span class="application">Python</span> sollever&agrave; l'eccezione <tt class="errorcode">ImportError</tt>, che
                        	noi cattureremo.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.2.2"><img src="http://it.diveintopython.net/images/callouts/2.png" alt="2" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Ok, non abbiamo <tt class="filename">termios</tt>, perci&ograve; proviamo <tt class="filename">msvcrt</tt>, un modulo
                        	specifico di Windows, che fornisce un <span class="acronym">API</span> per molte
                        	funzioni utili del Microsoft
                        	<span class="application">Visual C++</span> run-time. Se l'import
                        	fallisce, <span class="application">Python</span> sollever&agrave; <tt class="errorcode">ImportError</tt> e noi cattureremo
                        	l'eccezione.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.2.3"><img src="http://it.diveintopython.net/images/callouts/3.png" alt="3" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Se i primi due non funzionano, proviamo ad importare una
                        	funzione da <tt class="filename">EasyDialogs</tt>, che &egrave; un modulo specifico di
                        	<span class="abbrev">Mac</span> <span class="acronym">OS</span> che provvede a funzioni di dialogo popup di vario
                        	tipo. Se, ancora una volta, questo import fallisce, <span class="application">Python</span>
                        	sollever&agrave; l'eccezione <tt class="errorcode">ImportError</tt>, che noi cattureremo.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.2.4"><img src="http://it.diveintopython.net/images/callouts/4.png" alt="4" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Nessuno di questi moduli specifici di piattaforma sono
                        	disponibili (il che &egrave; possibile, visto che <span class="application">Python</span> &egrave; stato
                        	portato su molte differenti piattaforme), perci&ograve; dobbiamo
                        	puntare su una funzione standard di input delle password (che
                        	&egrave; definita da qualche altra parte nel modulo <tt class="filename">getpass</tt>).
                        	Notate cosa stiamo facendo: stiamo assegnando la funzione
                        	<tt class="function">default_getpass</tt> alla variabile
                        	<tt class="varname">getpass</tt>. Se leggete la documentazione
                        	ufficiale di <tt class="filename">getpass</tt>, vi spiegher&agrave; che il modulo
                        	<tt class="function">getpass</tt> definisce una funzione
                        	<tt class="varname">getpass</tt>. Questo &egrave; ci&ograve; che fa: passa
                        	<tt class="function">getpass</tt> alla giusta funzione per la
                        	vostra piattaforma. Quindi, quando chiamate la funzione
                        	getpass,
                        	state realmente chiamando una funzione specifica per la vostra
                        	piattaforma, che questo codice ha fatto per voi. Non avete
                        	bisogno di conoscere o di far caso alla piattaforma su cui
                        	gira il vostro programma; limitatevi a chiamare
                        	<tt class="function">getpass</tt> e questi far&agrave; sempre la cosa
                        	giusta.
                        
                     </td>
</tr>
<tr>
<td width="12" valign="top" align="left"><a href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#fileinfo.exceptions.2.5"><img src="http://it.diveintopython.net/images/callouts/5.png" alt="5" border="0" width="12" height="12" /></a>
</td>
<td valign="top" align="left">
                        	Un blocco <tt class="literal">try...except</tt> pu&ograve; avere una clausola <tt class="literal">else</tt>,
                        	come l'istruzione <tt class="literal">if</tt>. Se nessuna eccezione &egrave;
                        	sollevata durante il blocco  <tt class="literal">try</tt>, la
                        	clausola <tt class="literal">else</tt> viene 
                        	eseguita di seguito. In questo caso, questo significa che
                        	<tt class="literal">from EasyDialogs import AskPassword</tt>
                        	funziona, per cui noi dovremmo legare
                        	<tt class="varname">getpass</tt> alla funzione
                        	<tt class="function">AskPassword</tt>. Ognuno degli altri blocchi
                        	<tt class="literal">try...except</tt> hanno clausole <tt class="literal">else</tt> simili, per legare
                        	<tt class="varname">getpass</tt> alla funzione appropriata, quando
                        	troviamo un <tt class="literal">import</tt> che funzioni.
                        
                     </td>
</tr>
</table>
</div>
</div>
<div class="furtherreading">
<h3>Ulteriori letture</h3>
<ul>
<li>
<a href="http://it.diveintopython.net/doc/current/tut/tut.html"><i class="citetitle"><span class="application">Python</span> Tutorial</i></a> discute
                  <a href="http://it.diveintopython.net/doc/current/tut/node10.html#SECTION0010400000000000000000">della definizione
                     e del sollevamento delle vostre eccezioni, ed infine della gestione di eccezioni
                     multiple</a>, tutto in una volta.
                  
               </li>
<li>
<a href="http://it.diveintopython.net/doc/current/lib/"><i class="citetitle"><span class="application">Python</span> Library Reference</i></a> riassume
                  <a href="http://it.diveintopython.net/doc/current/lib/module-exceptions.html">tutte le eccezioni built-in</a>.
                  
               </li>
<li>
<a href="http://it.diveintopython.net/doc/current/lib/"><i class="citetitle"><span class="application">Python</span> Library Reference</i></a> documenta il
                  	<a href="http://it.diveintopython.net/doc/current/lib/module-getpass.html">modulo <tt class="filename">getpass</tt></a>.
                  
               </li>
<li>
<a href="http://it.diveintopython.net/doc/current/lib/"><i class="citetitle"><span class="application">Python</span> Library Reference</i></a> documenta il
                  <a href="http://it.diveintopython.net/doc/current/lib/module-traceback.html">modulo
                     <tt class="filename">traceback</tt></a>,
                  	che consente un accesso a basso livello agli attributi delle
                  	funzioni dopo che &egrave; stata sollevata un'eccezione.
                  
               </li>
<li>
<a href="http://it.diveintopython.net/doc/current/ref/"><i class="citetitle"><span class="application">Python</span> Reference Manual</i></a> discute  del funzionamento interno del
                  	<a href="http://it.diveintopython.net/doc/current/ref/try.html">blocco <tt class="literal">try...except</tt></a>.
                  
               </li>
</ul>
</div>
<div class="footnotes">
<h3 class="footnotetitle">Footnotes</h3>
<div class="footnote">
<p><sup>[<a name="ftn.d0e10936" href="http://it.diveintopython.net/object_oriented_framework/handling_exceptions.html#d0e10936">6</a>] </sup>
                     O, come alcuni pignoli farebbero notare, il vostro programma
                     effettuerebbe un'azione illegale. Qualunque.
                     
               </p>
</div>
</div>
</div>
<table class="Footer" width="100%" border="0" cellpadding="0" cellspacing="0" summary="">
<tr>
<td width="35%" align="left"><br /><a class="NavigationArrow" href="http://it.diveintopython.net/object_oriented_framework/private_functions.html">&lt;&lt;&nbsp;Funzioni private</a></td>
<td width="30%" align="center"><br />&nbsp;<span class="divider">|</span>&nbsp;<a href="http://it.diveintopython.net/object_oriented_framework/index.html#fileinfo.divein" title="4.1.&nbsp;Immergersi">1</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/importing_modules.html" title="4.2.&nbsp;Importare i moduli usando from module import">2</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/defining_classes.html" title="4.3.&nbsp;Definire classi">3</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/instantiating_classes.html" title="4.4.&nbsp;Istanziare classi">4</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/userdict.html" title="4.5.&nbsp;UserDict: una classe wrapper">5</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/special_class_methods.html" title="4.6.&nbsp;Metodi speciali per le classi">6</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/special_class_methods2.html" title="4.7.&nbsp;Metodi speciali di classe avanzati">7</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/class_attributes.html" title="4.8.&nbsp;Attributi di classe">8</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/private_functions.html" title="4.9.&nbsp;Funzioni private">9</a> <span class="divider">|</span> <span class="thispage">10</span> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/file_objects.html" title="4.11.&nbsp;Oggetti file">11</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/for_loops.html" title="4.12.&nbsp;Cicli for ">12</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/more_on_modules.html" title="4.13.&nbsp;Ancora sui moduli">13</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/os_module.html" title="4.14.&nbsp;Il modulo os">14</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/all_together.html" title="4.15.&nbsp;Mettere tutto insieme">15</a> <span class="divider">|</span> <a href="http://it.diveintopython.net/object_oriented_framework/summary.html" title="4.16.&nbsp;Sommario">16</a>&nbsp;<span class="divider">|</span>&nbsp;
            </td>
<td width="35%" align="right"><br /><a class="NavigationArrow" href="http://it.diveintopython.net/object_oriented_framework/file_objects.html">Oggetti file&nbsp;&gt;&gt;</a></td>
</tr>
<tr>
<td colspan="3"><br /></td>
</tr>
</table>
<div class="Footer">
<p class="copyright">Copyright &copy; 2000, 2001, 2002, 2003 <a href="mailto:josh@servercobra.com">Mark Pilgrim</a></p>
<p class="copyright">Copyright &copy; 2003 Si veda l'appendice <span class="emphasis"><em>E: "Storia delle revisioni"</em></span></p>
</div>
</body>
</html>
